"""A simple API for creating and using playing cards"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_card.ipynb.

# %% auto 0
__all__ = ['suits', 'ranks', 'Card']

# %% ../00_card.ipynb 3
suits = ["♠", "♥", "♦", "♣"]
ranks = [None, "A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K"]

# %% ../00_card.ipynb 11
class Card:
    "A playing card"
    def __init__(self, 
                 suit: int,  # An index into `suits`
                 rank: int  # An index into `ranks`
                 ):
        self.suit = suit
        self.rank: int = rank

    def __str__(self):
        return f"{ranks[self.rank]}{suits[self.suit]}"
    
    __repr__ = __str__


    def __eq__(self, card: 'Card'):
        return self.rank == card.rank and self.suit == card.suit
    
    def __lt__(self, card: 'Card'):
        return self.rank < card.rank
